vdj/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'groups/([0-9]+)/$', views.group, name='group'),
    url(r'add/$', views.add_lesson, name='add_lesson'),
]

vesnadance_journal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^journal/', include('vdj.urls')),
]

vdj/models.py
from django.db import models
from django.forms import ModelForm, Textarea, DateInput, DateField


class Venue(models.Model):
    name = models.CharField(max_length=200, verbose_name="название")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "зал"
        verbose_name_plural = "залы"


class Teacher(models.Model):
    name = models.CharField(max_length=200, verbose_name="имя")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "преподаватель"
        verbose_name_plural = "преподаватели"


class Group(models.Model):
    name = models.CharField(max_length=200, verbose_name="название")
    standard_teacher_fee = models.IntegerField(default=1500, verbose_name="оплата преподавателя")
    teachers = models.ManyToManyField(Teacher)
    venues = models.ManyToManyField(Venue)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "группа"
        verbose_name_plural = "группы"


class Student(models.Model):
    name = models.CharField(max_length=200, verbose_name="имя")
    phone = models.CharField(max_length=200, verbose_name="номер телефона")
    has_discount = models.BooleanField(default=False, verbose_name="право на скидку")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "ученик"
        verbose_name_plural = "ученики"


class Lesson(models.Model):
    date = models.DateField("дата")
    group = models.ForeignKey(Group, verbose_name="группа", null=True)
    teachers = models.ManyToManyField(Teacher, through='TaughtBy')

    venue = models.ForeignKey(Venue, verbose_name="зал")
    students = models.ManyToManyField(Student, through='AttendedBy', verbose_name="ученики")
    revenue = models.IntegerField("выручка", default=0)
    rent = models.IntegerField("аренда", default=0)
    comment = models.TextField("комментарий", blank=True)

    def __str__(self):
        return ' '.join([self.group.__str__(), self.date.__str__()])

    class Meta:
        verbose_name = "занятие"
        verbose_name_plural = "занятия"

class Subscription(models.Model):
    SUBSCRIPTION_TYPES = (
        ('10', '10 занятий'),
        ('15', '15 занятий'),
    )
    start_date = models.DateField("дата")
    expiry_date = models.DateField("дата")
    student = models.ForeignKey(Student, verbose_name="ученик")
    type = models.CharField(max_length=2, choices=SUBSCRIPTION_TYPES)

    class Meta:
        verbose_name = "абонемент"
        verbose_name_plural = "абонементы"

class TaughtBy(models.Model):
    teacher = models.ForeignKey(Teacher, verbose_name="преподаватель")
    lesson = models.ForeignKey(Lesson, verbose_name="занятие")
    fee = models.IntegerField(verbose_name="гонорар")

    class Meta:
        verbose_name = "преподаватель"
        verbose_name_plural = "преподаватели"

class AttendedBy(models.Model):
    student = models.ForeignKey(Student, verbose_name="ученик")
    lesson = models.ForeignKey(Lesson, verbose_name="занятие")


class LessonForm(ModelForm):
    date = DateField()
    class Meta:
        model = Lesson
        fields = ['date', 'group', 'teachers', 'venue', 'comment']
        widgets = {
            'date': DateInput,
            'name': Textarea(attrs={'cols': 80, 'rows': 5}),
        }

vdj/views.py
from django.shortcuts import render

from .models import Group, Lesson, LessonForm


def index(request):
    groups = Group.objects.all()
    return render(request, 'vdj/index.html', {'groups': groups})


def group(request, group_id):
    lessons = Lesson.objects.filter(group_id=group_id)
    return render(request, 'vdj/group.html', {'lessons': lessons})

def add_lesson(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LessonForm(request.POST)
        # check whether it's valid:
        '''if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')'''

    # if a GET (or any other method) we'll create a blank form
    else:
        form = LessonForm()

    return render(request, 'vdj/add_lesson.html', {'form': form})

vdj/templates/vdj/add_lesson.html
<html>
<head>
    <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/themes/redmond/jquery-ui.css" rel="Stylesheet" />
    <script language="javascript" type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js"></script>

</head>

{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container">
<h1>Добавить занятие</h1>
<form action="{% url 'add_lesson' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Добавить
        </button>
    {% endbuttons %}
</form>
</div>
<script type="text/javascript">
  $(function(){
    $("#id_date").datepicker();
  });
</script>
</html>

vdj/templates/vdj/group.html
{% if lessons %}
    <table>
    {% for lesson in lessons %}
        <tr><td>{{lesson.date|date:"d.m.Y"}}</td><td>{{lesson.rent}}</td><td></td><td></td></tr>
    {% endfor %}
    </table>
{% else %}
    <p>No data.</p>
{% endif %}

vdj/templates/vdj/index.html
{% if groups %}
    <ul>
    {% for group in groups %}
        <li><a href="{% url 'group' group.id %}">{{ group.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No data.</p>
{% endif %}